### ISSUE TITLE
Changed To CryptonoteEvoV3 But Still Get: "Failed to add genesis block to blockchain"

### ISSUE THREAD

**Issue by hifromjarrod** [Nur1Labs/CryptonoteEvoV3-CLI#2]
So earlier today I downloaded CryptonoteEvo-CLI and i got the error: "Failed to add genesis block to blockchain". I recently tried again with CryptonoteEvoV3-CLI and got a very similar error when I type ./jormocoind i get the following.

`15:35:08.431796 INFO jormocoin v3.0.1.20.LamdaDriver-v3()
15:35:08.432565 INFO Module folder: ./jormocoind
15:35:08.433557 INFO Initializing p2p server...
15:35:08.434031 INFO Generated new peer ID: 3465300028868979200
15:35:08.434097 INFO Binding on 0.0.0.0:17236
15:35:08.434240 INFO Net service bound on 0.0.0.0:17236
15:35:08.434297 INFO Attempting to add IGD port mapping.
15:35:09.521785 INFO Added IGD port mapping.
15:35:09.522024 INFO P2p server initialized OK
15:35:09.522167 INFO Initializing core...
15:35:09.523226 INFO Blockchain not loaded, generating genesis block.
15:35:09.523476 INFO Block <8ff57fa129361def9c60b4698962be628b5889768ad80029207c7325afb7475a> has wrong major version: 1, at height 0 expected version is 3
15:35:09.523710 ERROR Failed to add genesis block to blockchain
15:35:09.523847 ERROR Failed to initialize blockchain storage
15:35:09.524025 ERROR Failed to initialize core
15:35:09.524295 INFO Mining has been stopped, 0 finished
SwappedVector cache hits: 0, misses: 0 (nan%)`

Thank you.

**Comment by Shiro20** [comment]
try ./daemon --print-genesis-tx

**Comment by hifromjarrod** [comment]
> try ./daemon --print-genesis-tx

That worked but when i did ./daemon i got the same error as above

**Comment by Shiro20** [comment]
git pull https://github.com/Nur1Labs/CryptonoteEvoV3-CLI/commit/e437f1ad09644dc365527e386f3ca9562cf357e3

and try git submodule init && git submodule update --remote

**Comment by hifromjarrod** [comment]
It worked! Thank you so much.

Love the project by the way!

**Comment by FndNur1Labs** [comment]
ok no problem
