### ISSUE TITLE
mined block failed verification

### ISSUE THREAD

**Issue by sunnymiesta** [Nur1Labs/CryptonoteEvoV3-CLI#4]
Hi,
I have successfully compiled this version of cryptonote, but when I try start_mining using the daemon, I keep getting the below errors. I've tried leaving the settings in CryptoNoteConfig.h as defaults and just generate the genesis block and go. But I still keep getting the same error below when trying to mine. I've made sure there is no old blockchain data existing and started fresh each time. Any ideas what the issue could be?  Thanks in advance, 

2018-Jun-04 01:59:12.492270 INFO    Found block for difficulty: 1
2018-Jun-04 01:59:12.492753 ERROR   Failed to get block hash, possible block has invalid format
2018-Jun-04 01:59:12.493838 ERROR   mined block failed verification
2018-Jun-04 01:59:12.601081 INFO    Found block for difficulty: 1
2018-Jun-04 01:59:12.601509 ERROR   Failed to get block hash, possible block has invalid format
2018-Jun-04 01:59:12.602533 ERROR   mined block failed verification

**Comment by FndNur1Labs** [comment]
issue come from block_major version. since used 1 need reset to one

https://github.com/Nur1Labs/CryptonoteEvoV3-CLI/commit/b8625a1dbe32d31acb664e5bbc6aea204e1f2663

solved

**Comment by sunnymiesta** [comment]
thanks for this, but I just tried again and receive the same error.
Can u pls provide any further instruction to resolve this?
thanks very much,
sunny

**Comment by Shiro20** [comment]
used transaction 1 it's fixed as it's original

**Comment by hifromjarrod** [comment]
@sunnymiesta I am having the same issue. were you able to fix it? thank you

**Comment by sunnymiesta** [comment]
Thanks @Shiro20 changes applied, sorry to report, the same issue persists.
@hifromjarrod not yet, still trying to work it through.

**Comment by FndNur1Labs** [comment]
this cause timestamp you start for linux used command below. terminal

`date +%s`

and do clean all .chain folder at home....

do this

`,/daemon --print-genesis-tx`

**Comment by sunnymiesta** [comment]
The cause of the issue is UPGRADE_HEIGHT_V3 = 2;
Changing the value to 100, allows mining to work until it reaches block 100. after that the same error occurs. A workaround is to set to block 600000000, which means it won't trigger upgradev3 at all.

**Comment by FndNur1Labs** [comment]
this our fork : https://github.com/CatalystCash/Catalyst

all fine until now

https://pool.catalyst.cash/#worker_stats

from start used V2 then V3 on next height. try increase both

**Comment by FndNur1Labs** [comment]
this one without issue too https://github.com/RAY-official/Photon-Coin

**Comment by Shiro20** [comment]
@sunnymiesta i think that bug on major thing. actually for major block 2-3 got for v3 function. so feel easy used v2 and you can see another sample who alread running. like @Catalyst do

**Comment by hifromjarrod** [comment]
is there a fix without having to change upgrade height?

**Comment by hifromjarrod** [comment]
anyone find a fix that does not require changing block height

**Comment by FndNur1Labs** [comment]
there will be next patch this night for fixed on granted reward zone. cuz zone now used block_major_3 we fixed soon

**Comment by jarrosha** [comment]
it looks like you just increased the upgrade height can (did) you fix the problem that happens when you reach the upgrade height it stops are gives you an error

**Comment by hifromjarrod** [comment]
does that fix the problem of what happens when you reach the upgrade height v3. where it either stops going up at all going up or spams errors

**Comment by FndNur1Labs** [comment]
will did try by someone.  by parent block thing
