### ISSUE TITLE
failed compile at payment_gate

### ISSUE THREAD

**Issue by mygirl8893** [Nur1Labs/CryptonoteEvoV3-CLI#7]
Seek help to solve this ,

[ 39%] Building CXX object src/CMakeFiles/payment_gate.dir/payment_gate/PaymentS                     erviceJsonRpcServer.cpp.o
[ 40%] Building CXX object src/CMakeFiles/payment_gate.dir/payment_gate/WalletSe                     rvice.cpp.o
In file included from /home/fork/evo3/src/payment_gate/WalletService.cpp:26:0:
/home/fork/evo3/src/wallet/WalletGreen.h:29:16: error: ‘virtual void CryptoNote:                     :WalletGreen::initialize(const string&, const string&)’ marked ‘override’, but d                     oes not override
   virtual void initialize(const std::string& path, const std::string& password)
                ^
/home/fork/evo3/src/payment_gate/WalletService.cpp: In function ‘Crypto::Hash Pa                     ymentService::{anonymous}::parsePaymentId(const string&)’:
/home/fork/evo3/src/payment_gate/WalletService.cpp:64:8: warning: unused variabl                     e ‘r’ [-Wunused-variable]
   bool r = Common::podFromHex(paymentIdStr, paymentId);
        ^
/home/fork/evo3/src/payment_gate/WalletService.cpp: In function ‘void PaymentSer                     vice::generateNewWallet(const CryptoNote::Currency&, const PaymentService::Walle                     tConfiguration&, Logging::ILogger&, System::Dispatcher&)’:
/home/fork/evo3/src/payment_gate/WalletService.cpp:379:100: error: invalid new-e                     xpression of abstract class type ‘CryptoNote::WalletGreen’
 wallet = new CryptoNote::WalletGreen(dispatcher, currency, *nodeStub, logger);
                                                                             ^
In file included from /home/fork/evo3/src/payment_gate/WalletService.cpp:26:0:
/home/fork/evo3/src/wallet/WalletGreen.h:20:7: note:   because the following vir                     tual functions are pure within ‘CryptoNote::WalletGreen’:
 class WalletGreen : public IWallet,
       ^
In file included from /home/fork/evo3/src/payment_gate/WalletService.h:6:0,
                 from /home/fork/evo3/src/payment_gate/WalletService.cpp:1:
/home/fork/evo3/include/IWallet.h:118:16: note:         virtual void CryptoNote:                     :IWallet::initialize(const string&)
   virtual void initialize(const std::string& password) = 0;
                ^
/home/fork/evo3/src/payment_gate/WalletService.cpp:385:58: error: no matching fu                     nction for call to ‘CryptoNote::IWallet::initialize(const string&, const string&                     )’
   wallet->initialize(conf.walletFile, conf.walletPassword);
                                                          ^
In file included from /home/fork/evo3/src/payment_gate/WalletService.h:6:0,
                 from /home/fork/evo3/src/payment_gate/WalletService.cpp:1:
/home/fork/evo3/include/IWallet.h:118:16: note: candidate: virtual void CryptoNo                     te::IWallet::initialize(const string&)
   virtual void initialize(const std::string& password) = 0;
                ^
/home/fork/evo3/include/IWallet.h:118:16: note:   candidate expects 1 argument,                      2 provided
/home/fork/evo3/src/payment_gate/WalletService.cpp:387:58: error: no matching fu                     nction for call to ‘CryptoNote::IWallet::initialize(const string&, const string&                     )’
   wallet->initialize(conf.walletFile, conf.walletPassword);
                                                          ^
In file included from /home/fork/evo3/src/payment_gate/WalletService.h:6:0,
                 from /home/fork/evo3/src/payment_gate/WalletService.cpp:1:
/home/fork/evo3/include/IWallet.h:118:16: note: candidate: virtual void CryptoNo                     te::IWallet::initialize(const string&)
   virtual void initialize(const std::string& password) = 0;
                ^
/home/fork/evo3/include/IWallet.h:118:16: note:   candidate expects 1 argument,                      2 provided
src/CMakeFiles/payment_gate.dir/build.make:101: recipe for target 'src/CMakeFile                     s/payment_gate.dir/payment_gate/WalletService.cpp.o' failed
make[3]: *** [src/CMakeFiles/payment_gate.dir/payment_gate/WalletService.cpp.o]                      Error 1
make[3]: Leaving directory '/home/fork/evo3/build/release'
CMakeFiles/Makefile2:1320: recipe for target 'src/CMakeFiles/payment_gate.dir/al                     l' failed
make[2]: *** [src/CMakeFiles/payment_gate.dir/all] Error 2
make[2]: Leaving directory '/home/fork/evo3/build/release'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/fork/evo3/build/release'
Makefile:20: recipe for target 'build-release' failed
make: *** [build-release] Error 2

**Comment by sunnymiesta** [comment]
Hi, just a suggestion did u make sure to run command 'git submodule init && git submodule update --remote'   before make.
I've successfully compiled on ubuntu 16.04

**Comment by mygirl8893** [comment]
Hi, I did. Mine ubuntu 16.04 too but failed.
What about your GCC/C++ version ?

**Comment by Shiro20** [comment]
try debian and old os. it's work. soon possible next checkpoint fixed

**Comment by FndNur1Labs** [comment]
@mygirl8893 that cuz this.

https://github.com/Nur1Labs/CryptonoteEvoV3-CLI/commit/ffba2b7c597cf264eaf0f8114ee325fb433c6bad

thank for report we keep improve our codes

**Comment by mygirl8893** [comment]
@FndNur1Labs  thanks, error solved
