### ISSUE TITLE
GUI wallet

### ISSUE THREAD

**Issue by sunnymiesta** [Nur1Labs/CryptonoteEvoV3-CLI#8]
Hi,
Not sure if this is the place to raise this,
Are you please able to help with creating a GUI wallet? If you can point me in the right direction that would be great.
Thanks very much in advance,
Sunny

**Comment by FndNur1Labs** [comment]
@sunnymiesta i alread invite you to join cryptonote in here. so you can explore like 

https://github.com/orgs/Nur1Labs/teams/cryptonoteevo-development/repositories

**Comment by hifromjarrod** [comment]
@FndNur1Labs that link doesnt work for me.

**Comment by FndNur1Labs** [comment]
we not provided the GUI. try another GUI you can used here....soon we hope can develop GUI. not have time on GUI usual on cores.
